[versions]
axion-release = "1.21.0"
bytebuddy = "1.17.8"
checker-qual = "3.52.0"
dbunit = "3.0.0"
derby = "10.17.1.0"
errorprone = "2.44.0"
errorprone-plugin = "4.3.0"
guava = "33.5.0-jre"
h2 = "2.4.240"
hsqldb = "2.7.4"
jreleaser = "1.21.0"
jspecify = "1.0.0"
junit = "6.0.1"
mockito = "5.20.0"
mssql-jdbc = "13.2.1.jre11"
mysql-connector = "9.5.0"
nullaway = "0.12.12"
oracle-ojdbc = "23.26.0.0.0"
postgresql = "42.7.8"
slf4j = "2.0.17"
spotless = "8.1.0"
testcontainers = "2.0.1"
version-catalog-update = "1.0.1"

[libraries]
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }
dbunit = { module = "org.dbunit:dbunit", version.ref = "dbunit" }
derby-client = { module = "org.apache.derby:derbyclient", version.ref = "derby" }
derby-embedded = { module = "org.apache.derby:derby", version.ref = "derby" }
derby-tools = { module = "org.apache.derby:derbytools", version.ref = "derby" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-refaster = { module = "com.google.errorprone:error_prone_refaster", version.ref = "errorprone" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hsqldb = { module = "org.hsqldb:hsqldb", version.ref = "hsqldb" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssql-jdbc" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
oracle-ojdbc17 = { module = "com.oracle.database.jdbc:ojdbc17", version.ref = "oracle-ojdbc" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-mssqlserver = { module = "org.testcontainers:testcontainers-mssqlserver" }
testcontainers-mysql = { module = "org.testcontainers:testcontainers-mysql" }
testcontainers-oracle-free = { module = "org.testcontainers:testcontainers-oracle-free" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }

[plugins]
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
